"""add role field to users

Revision ID: 6fdf0c093427
Revises: e7100ca75dbe
Create Date: 2025-04-17 23:11:30.342784

"""
import enum
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6fdf0c093427'
down_revision: Union[str, None] = 'e7100ca75dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

class UserRole(enum.Enum):
    USER = "USER"
    ADMIN = "ADMIN"


user_role_enum = postgresql.ENUM(UserRole, name='userrole')

def upgrade() -> None:
    user_role_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
    user_role_enum.drop(op.get_bind(), checkfirst=True)
